# Generated by Django 5.2.3 on 2025-06-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionrequest',
            name='arrival_time',
            field=models.CharField(default='Night', max_length=100),
        ),
        migrations.AddField(
            model_name='predictionrequest',
            name='destination_city',
            field=models.CharField(default='Mumbai', max_length=100),
        ),
        migrations.AddField(
            model_name='predictionrequest',
            name='stops',
            field=models.CharField(default='zero', max_length=100),
        ),
        migrations.AlterField(
            model_name='predictionrequest',
            name='airline',
            field=models.CharField(default='SpiceJet', max_length=100),
        ),
        migrations.AlterField(
            model_name='predictionrequest',
            name='cls',
            field=models.CharField(default='Economy', max_length=100),
        ),
        migrations.AlterField(
            model_name='predictionrequest',
            name='days_left',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='predictionrequest',
            name='departure_time',
            field=models.CharField(default='Evening', max_length=100),
        ),
        migrations.AlterField(
            model_name='predictionrequest',
            name='duration',
            field=models.CharField(default='2.17', max_length=100),
        ),
        migrations.AlterField(
            model_name='predictionrequest',
            name='flight',
            field=models.CharField(default='SG-8709', max_length=100),
        ),
        migrations.AlterField(
            model_name='predictionrequest',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='predictionrequest',
            name='source_city',
            field=models.CharField(default='Delhi', max_length=100),
        ),
    ]
